name: 项目部署
  on: push
  jobs:
    npm-build:
      name: 打包
      runs-on: ubuntu-latest
      steps:
        - name: 读取仓库代码
          uses: actions/checkout@v4
        - name: 安装依赖和项目打包
          run: |
            pnpm install
            pnpm run build
